---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-key-value-teamdev-com-v1beta1-keyvaluedata
  failurePolicy: Fail
  name: mkeyvaluedata.kb.io
  rules:
  - apiGroups:
    - key-value.teamdev.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - keyvaluedata
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-key-value-teamdev-com-v1beta1-keyvaluedata
  failurePolicy: Fail
  name: vkeyvaluedata.kb.io
  rules:
  - apiGroups:
    - key-value.teamdev.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - keyvaluedata
  sideEffects: None
