apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kv-server.fullname" . }}
  labels:
      {{- include "kv-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kv-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kv-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.envVars }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          ports:
            - name: {{ .Values.portName }}
              containerPort: {{ .Values.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volumeName }}
              mountPath: {{ .Values.mountPath }}
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistenceVolumeClaim.name }}