apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: {{.Values.namespace}}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
     {{- include "kv-server.selectorLabels" . | nindent 6 }}
  ports:
    {{ toYaml .Values.servers | nindent 4 }}
