apiVersion: v1
kind: Service
metadata:
  name: {{ include "kv-server.serviceAccountName" . }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
     {{- include "kv-server.selectorLabels" . | nindent 6 }}
  ports:
    {{ toYaml .Values.servers | nindent 4 }}
