apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  labels:
    type: local
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/prokop/Programming/timdev/storage/persistence
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: miprokop/storage_server:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCAL_SSL_KEY
              value: persistence/localhost.pem
            - name: LOCAL_SSL_CERT
              value: persistence/localhost-key.pem
            - name: K8S_SSL_KEY
              value: persistence/k8s.key
            - name: K8S_SSL_CERT
              value: persistence/k8s.crt
            - name: SERVER_URL
              value: https://localhost:8080
          ports:
            - name: http-server
              containerPort: 8080
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: storage-volume
              mountPath: /root/persistence
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage-pvc
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: storage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage-d
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage
  ports:
    - name: storage-http
      protocol: TCP
      port: 8080
      targetPort: http-server
