apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  type: NodePort
  selector:
    app: storage
  ports:
    - name: storage-http
      protocol: TCP
      port: 8081
      targetPort: http-server
