apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi