apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: operator-controller-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /Users/prokop/Programming/timdev/storage/persistence
  storageClassName: hostpath
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operator-controller-pvc
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: operator-controller-pv